### ISSUE TITLE
Two "welcome" apps reported

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/greetbot#10]
Report from Maya B on #codebuddies-meta: "Hi - I’ve got the “CodeBuddies Welcome” app twice on my account for some reason - went through it and clicked accept which cleared the active message on one of the two but not the other - so always looks like there’s a waiting message for me"

**Comment by BethanyG** [comment]
Not sure if this is a result of having two configurations - or if the `user_join` fired twice, or some other issue.  Investigating. 

Reproduced on Production.  `user_join` appears to be firing twice, and then once the [accept] button is pushed, the DB flag prevents the second message from clearing.  Will deploy production code onto staging and see if I can reproduce the issue there.

**UPDATE:**  Wasn't able to reproduce on Staging.  "re-installed" existing code into CodeBuddies workspace, and the problem appeared to go away.  Needs an additional re-test.  @lpatmo can you do the honors?  Will send you a join link via DM.  Thanks!!

**Comment by BethanyG** [comment]
re-installing the application into the Slack workspace via the Slack app interface appeared to do the trick.  Something about the permissions changed on the app, and that **_seems_** to have been the problem, although I am not totally clear on what exactly broke.  Two tests of new user join seem to show that the problem is no longer occurring.  Closing issue for now.
